// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJTQvObOGKt913qUaa3CqkakHM_doPhMs',
    appId: '1:835959166049:web:98a9a31bd8e00f689e4620',
    messagingSenderId: '835959166049',
    projectId: 'notesmart-41a84',
    authDomain: 'notesmart-41a84.firebaseapp.com',
    storageBucket: 'notesmart-41a84.firebasestorage.app',
    measurementId: 'G-DF1KVCTC82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWooscdTYQv67AiwtbuIlYGTQag7mr8k',
    appId: '1:835959166049:android:b31fdba8f243ea7a9e4620',
    messagingSenderId: '835959166049',
    projectId: 'notesmart-41a84',
    storageBucket: 'notesmart-41a84.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIH8vobq5xngXhfsBn07tXLgSDcYZqGFs',
    appId: '1:835959166049:ios:172fead1704b02df9e4620',
    messagingSenderId: '835959166049',
    projectId: 'notesmart-41a84',
    storageBucket: 'notesmart-41a84.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIH8vobq5xngXhfsBn07tXLgSDcYZqGFs',
    appId: '1:835959166049:ios:172fead1704b02df9e4620',
    messagingSenderId: '835959166049',
    projectId: 'notesmart-41a84',
    storageBucket: 'notesmart-41a84.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJTQvObOGKt913qUaa3CqkakHM_doPhMs',
    appId: '1:835959166049:web:c4b4e4a3938c6eae9e4620',
    messagingSenderId: '835959166049',
    projectId: 'notesmart-41a84',
    authDomain: 'notesmart-41a84.firebaseapp.com',
    storageBucket: 'notesmart-41a84.firebasestorage.app',
    measurementId: 'G-8ERTNE806T',
  );
}
